name: Deploy to Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results
        

  deploy:
    name: Deploy to Cloud
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: test-results

      - name: Deploy to Cloud
        run: |
          docker-compose up -d
      
      - name: Stop container
        run: |
          docker-compose down

  notify-slack:
    name: Notify on Slack
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ always() }}

    steps:
      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: "Tests ${{ job.status }} on branch ${{ github.ref }} in repository ${{ github.repository }}"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
