name: Deploy to Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2.4.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Deploy to Cloud
        run: |
          docker-compose up -d
      
      - name: Stop container
        if: always()
        run: |
          docker compose down

  notify-slack:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
    - name: Notify on Slack
      uses: rtCamp/action-slack-notify@v2
      with:
        status: ${{ job.status }}
        text: "Tests ${{ job.status }} on branch ${{ github.ref }} in repository ${{ github.repository }}"
      env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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