name: Deploy to Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Start testing container
        run: |
          docker compose up --build -d --wait 

      - name: Deploy to Cloud
        run: |
          docker-compose up -d
      
      - name: Stop container
        if: always()
        run: |
          docker compose down
