name: Deploy to Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Setup Docker
        uses: docker/setup-docker@v2

      - name: Build and push Docker image
        run: |
          docker-compose build
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker-compose push

      - name: Deploy to Cloud
        run: |
          docker-compose up -d
